### ISSUE TITLE
关于 stm32F429

### ISSUE THREAD

**Issue by lo-ferris** [gqf2008/Xtask#7]
example 中的例子直接 可以 跑在 stm32F29 上面么

**Comment by gqf2008** [comment]
> example 中的例子直接 可以 跑在 stm32F29 上面么
stm32的都差不多 手头没有板子 没有试过

**Comment by gqf2008** [comment]
刚看了下，stm32f4的hal库是一样的，应该只要改下memory.x里的内存映射就可以了
