### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TCSYANG** [gqf2008/Xtask#9]
PS E:\rust\Xtask> cargo run --example notify --feaures=gd32vf103 --target riscv32imac-unknown-none-elf --release
error: unexpected argument '--feaures' found

  tip: a similar argument exists: '--features'

Usage: cargo.exe run --example [<NAME>] --features <FEATURES> [args]...

**Comment by gqf2008** [comment]
--feaures=gd32vf103 改为 --features=gd32vf103 试试
